apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes
  namespace: default
subsets:
- addresses:
  - ip: 192.168.0.1
  - ip: 192.168.0.2
  - ip: 192.168.0.3
  ports:
  - name: https
    port: 8443
    protocol: TCP
